### ISSUE TITLE
Integration with Alfred, LaunchBar

### ISSUE THREAD

**Issue by ylian** [HappenApps/Quiver#92]
Lots of power users use app launchers such as Alfred and LaunchBar. It would be nice to be able to run a few basic actions from these apps, e.g., search Quiver notes, create a new note.

What's really needed is to provide scripting support in Quiver. Then it would be easy to integrate with these app launchers.

**Comment by LeonardoGentile** [comment]
:+1:

**Comment by marksb** [comment]
:+1:

**Comment by eliasmaier** [comment]
👍

**Comment by robdecker** [comment]
:+1:

**Comment by dkarter** [comment]
:+1:

**Comment by januz** [comment]
That would be awesome!

**Comment by ylian** [comment]
After I finish the current update.

**Comment by lastobelus** [comment]
👍🏻

(but not as important to me as Services ;))

**Comment by asafge** [comment]
+1

**Comment by jiamingz42** [comment]
Great app. What is the process of the Alfred integration of Quiver?

**Comment by ylian** [comment]
@benjamin19890721 No process at the moment.

**Comment by pglombardo** [comment]
I'd like to see this too.  I've written Alfred workflows in the past.  Is there an public API somewhere for Quiver?  Couldn't find any docs.

Love v3.0 BTW.  Just killed off Evernote for good (finally).

**Comment by ylian** [comment]
@pglombardo No public API but working on it. Scripting support coming soon.

**Comment by mAAdhaTTah** [comment]
@ylian Is there an issue for scripting support we can follow? Will it support scripting in JavaScript?

**Comment by ylian** [comment]
I will set up a ticket when the scripting support is close to ready, to gather feedback. Yes it will support JavaScript.

**Comment by facetheheat** [comment]
👍🏻

**Comment by LavareX** [comment]
👍🏻

**Comment by ylian** [comment]
A couple scripts from @CustomComputerT, added here for my own reference:

http://customct.com/alfred-2-workflows

http://customct.com/launchbar

**Comment by ylian** [comment]
Created a page for Alfred/LaunchBar workflows: https://github.com/HappenApps/Quiver/wiki/Alfred-LaunchBar-Integration

I'm working on scripting support right now. I will send out a build in a day or two. 

Also here is a ticket for scripting support: https://github.com/HappenApps/Quiver/issues/247

I'm not sure at the moment how Alfred/LaunchBar workflows work with AppleScript/JXA, so keep two tickets open for now.

**Comment by ylian** [comment]
Here is the first draft of scripting support: https://dl.dropboxusercontent.com/u/3445731/Quiver-scripting-draft1.zip

In this first draft, only notebooks, notes, tags and a few basic properties are exposed. And they are read-only.

Let me know what else you need for your scripts and I will try to add.

Check the scripting dictionary for details:

![screen shot 2015-12-13 at 4 35 22 pm](https://cloud.githubusercontent.com/assets/984895/11769533/8ac7bd6e-a1b7-11e5-8626-741c997bb825.png)

**Comment by segphault** [comment]
I made an experimental Alfred workflow for searching Quiver notes. It uses Quiver's own SearchKit index file in order to perform efficient full-text searches. It's implemented in Python and I used PyObjC to dig into the SearchKit APIs. When the user selects a note from the search results, it uses a `quiver://` URL to open it.

[Quiver.zip](https://github.com/HappenApps/Quiver/files/159650/Quiver.zip)

**Comment by ylian** [comment]
@segphault Impressive work!

**Comment by julianmenzler** [comment]
@segphault That sounds nice! Unfortunately I don't get it to work. No output for any keyword.

**Comment by segphault** [comment]
@jmenzler if you wouldn't mind, could you try it with the debug panel open in the Alfred workspace view and let me know what error message pops up? I've found a few bugs that I'm working out (it breaks when the path to your Quiver files has a space in it because I forgot to have it reverse the url encoding for the path that SearchKit returns for the matched notes). I'll have an updated version shortly.

**Comment by julianmenzler** [comment]
@segphault Of course, here you go:

> `[ERROR: alfred.workflow.input.scriptfilter] Code 1: Traceback (most recent call last):
>   File "<string>", line 12, in <module>
>   File "quiver.py", line 26, in getData
>     with open (metaFile, "r") as f:
> IOError: [Errno 2] No such file or directory: u'/Users/username/Dropbox/Macs/App%20Data/Quiver/Quiver.qvlibrary/Tutorial.qvnotebook/D2A1CC36-CC97-4701-A895-EFC98EF47026.qvnote/meta.json'
> [ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 5.)'. Row (null), Col (null): 'Extra content at the end of the document' in XML:
> <?xml version='1.0'?>
> <items>
> [ERROR: alfred.workflow.input.scriptfilter] Code 1: Traceback (most recent call last):
>   File "<string>", line 12, in <module>
>   File "quiver.py", line 26, in getData
>     with open (metaFile, "r") as f:
> IOError: [Errno 2] No such file or directory: u'/Users/username/Dropbox/Macs/App%20Data/Quiver/Quiver.qvlibrary/47749668-B202-42A1-933D-285D44E164E8.qvnotebook/4E6F7D31-C958-42D6-9B7A-4E1BF3C3885E.qvnote/meta.json'`

**Comment by segphault** [comment]
@jmenzler yep, it's the URL encoding issue, as I suspected. Thanks for sending the error message. Here's an updated version of the workflow that should work: [Quiver.zip](https://github.com/HappenApps/Quiver/files/162121/Quiver.zip)

**Comment by julianmenzler** [comment]
Awesome, works fairly well now! Thanks a lot! Will you put it up on packal.org?

**Comment by segphault** [comment]
Great, I'm glad it's working now. :smile: I wasn't planning on putting it up on Packal right away, but I'll probably do it in the future as I add more features and want to start updating it regularly.

**Comment by julianmenzler** [comment]
Great! Looking forward to it.. 😉

**Comment by underscorephil** [comment]
@ylian are there plans to support note creation?

**Comment by AmadeusB** [comment]
👍🏻

**Comment by moubi** [comment]
Using Quiver with Alfred is a good way to go. As a programmer I need to find fairly quick any code related information - snippets, common problems, bookmarks. Usually what we do is to go search google or stackoverflow. 

I would like to first search my own knowledge base and then go to google. And this should happen faster, so I think `Cmd + Space -> quiver action` is the way to go. Doing as Mac native as possible.

**Comment by wonderffee** [comment]
Is it possible to search tags in Quiver with Alfred workflow? I really like one EverNote workflow([Evernote 8.991 (Evernote 6.06+ support): Search, Create, Append, set Reminders... All within Alfred](http://www.alfredforum.com/topic/840-evernote-8991-evernote-606-support-search-create-append-set-reminders-all-within-alfred/)) , it supports search Evernote tag by "ens #tag". I hope Quiver has the similar feature.

**Comment by JMichaelTX** [comment]
### Request for LaunchBar Support

I don't use Alfred, but I use LaunchBar extensively.
I could really use the ability to search Quiver from LaunchBar.  From there I can use LB's powerful "Send" feature to send it to any app I want.
